### ISSUE TITLE
Android 8.0 is the new minimum for all new android apps, gnustl_shared is removed in NDK r18

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/uno#109]
```
CMake Error at /Users/Valkyrie/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake:265 (message):
  gnustl_shared is no longer supported.  Please switch to either c++_shared
  or c++_static.  See
  https://developer.android.com/ndk/guides/cpp-support.html for more
  information.
```

**Comment by kusma** [comment]
@mortend: Sounds like this kinda important.

I think what @AndrewEQ is saying is that since we upgraded the NDK version, we broke pre-android-8 support. If that's the case, this is a bad regression in terms of device compatibility...

**Comment by kusma** [comment]
I'm also a bit unsure about what's going on with the stl-version here. I see one mention of gnustl_shared in `lib/UnoCore/Targets/Android/app/build.gradle`, but f99047247218c30cae5f8cb5c8d437b50a45c151 seems to have switched away from that... Is this some leftover or something?

**Comment by mortend** [comment]
Though, none of these patches are live in our current release of `fuse-studio`...

**Comment by AndrewEQ** [comment]
Yep, btw, where can I update the jdk download/install url for ```fuse install android```?

I know this was just for helping with onboarding of new people when you guys initially started but I still think its pretty neat/quick for new installs and for new devs.

**Comment by AndrewEQ** [comment]
...one thought I had the other day was: "why can't open source be polished and have all the bells and whistles too?" :)

**Comment by mortend** [comment]
It looks like the JDK URLs lives on the `fuse-studio` repo, in this file: https://github.com/fuse-open/fuse-studio/blob/57fc8d58d983556c069f4f17e0e2e1af5ce6bc77/Source/AndroidManager/JavaInstaller.cs#L15

**Comment by mortend** [comment]
I added a 'verify & close' label as I think the issues in this ticket are resolved.

@AndrewEQ: I have tested this on Android 7.1 and 8.1. If you have access to lower versions and want to test more devices before closing the ticket, I can provide you with an APK for testing.

**Comment by AndrewEQ** [comment]
Thanks @mortend, I'm going away for a few days but can test it as soon as I'm back :)

**Comment by AndrewEQ** [comment]
Cool, we tested an APK from a new build and it worked.
