### ISSUE TITLE
Consider calling nuget restore from build.sh

### ISSUE THREAD

**Issue by BeeWarloc** [fuse-open/uno#20]
Sometimes I forget to do nuget restore before building locally after `git clean` or changes in one of the `packages.config`, resulting in a failed build.

Doing `nuget restore` from `scripts/build.sh` should fix this, although it adds some extra seconds to its run time. Personally I think that's worth it.

**Comment by kusma** [comment]
I did this for fuselibs when consuming uno through NuGet, so I guess this requirement is pretty much de-facto anyway. So yeah, I think this would be a good move.
