### ISSUE TITLE
macOS Catalina - android build - Could not locate Android SDK or NDK

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/uno#213]
Ok, so I tried to install as usual (npm install android-build-tools -g) but couldn't because of write permissions, so I customised the npm global directory to ~/.npm-global (which is in the current user directory), was then able to complete the install but when building for android, it still gave the following error, even though the .unoconfig had the Android SDK & NDK paths:

```
node_modules/.bin/uno build -t=android
Uno 1.12.1 (build 352) macOS 10.15 x86_64 ae63e36
Copyright © 2018-present Fuse Open

Configuring  0.11 s                                                            
Target is up-to-date -- stopping build (pass --force to override)
Building Android app
ERROR: Could not locate the Android SDK or NDK.

These dependencies can be acquired by installing 'android-build-tools':

    npm install android-build-tools -g

(unknown): E0200: Android build failed
0.02 s

Build completed in 0.14 seconds
    1 error
```

**Comment by mortend** [comment]
Can you please paste the results of:
```
uno config
```
```
cat ~/.unoconfig
```

**Comment by mortend** [comment]
Oh, you might have to do a `--force` build after changing configs.

```
node_modules/.bin/uno build -t=android --force
```

**Comment by AndrewEQ** [comment]
Cool, yeah `--force` did the trick!

**Comment by mortend** [comment]
Shweet!

**Comment by ibuli** [comment]
Hi guys, I am still facing this issue,
Can you help?

**Comment by AndrewEQ** [comment]
If the above didn't help, what's your specific issue @ibuli ?

**Comment by ibuli** [comment]
Sorry for not being clear Andrew, I was trying to run the build on Windows Machine.
And the solutions you gave didn't work for me and were getting the same error.

Do I need to follow any other instructions for windows specifically?

**Comment by Paulofsr** [comment]
Hi guys!

This does not work on the mac. After setting the 64-bit rules to meet Android rules, I don't resolve this error.

 

> sudo node_modules/.bin/uno build -t=android --force
> Uno 1.14.0 (build 550) macOS 10.12 x86_64 118f137
> Copyright © 2018-present Fuse Open
> 
> Configuring  35.41 s                                                                                                                                                                
> Compiling syntax tree  8.47 s                                                                                                                                                       
> Generating code and data                                                                                                                                                            
> src/Firebase/Core.uno(43.6): W0000: Gradle.Dependency.Compile is deprecated -- please replace with Gradle.Dependency.Implementation
> 24.12 s                                                                                                                                                                           
> 
> Building Android app                                                                                                                                                                
> ERROR: Could not locate the Android SDK or NDK.
> 
> These dependencies can be acquired by installing 'android-build-tools':
> 
>     npm install android-build-tools -g
> 
> After installing, pass --force to make sure the new configuration is picked up.
> 
>     uno build android --force
> 
> (unknown): E0200: Android build failed
> 0.11 s
> 
> Build failed in 68.16 seconds
>     1 warning
>     1 error

 
And my fuse does not work build:

> fuse build
> Uno 1.10.0-rc1 (build 187) macOS 10.12 x86_64 b79b2df
> Copyright © 2018-present Fuse Open
> 
> Configuring
> 
> (unknown): E0100: Package Uno.Graphics.Utils:1.14.0 was not found
> (unknown): E0100: Package Uno.Graphics.Utils:1.14.0 was not found
> (unknown): E0100: Package Uno.Graphics.Utils:1.14.0 was not found
> 
> Build completed in 27.94 seconds
>     3 errors
> 
> fuse: Errors were encountered while building the project

**Comment by mortend** [comment]
@Paulofsr does installing Android Build Tools fix the problem?
```
npm install android-build-tools -g
```

If the above command does not work - please file a new issue at https://github.com/mortend/android-build-tools

**Comment by Paulofsr** [comment]
@mortend, unfortunately the installation did not works on my mac.

```
sudo npm install android-build-tools -g --force
Password:
npm WARN using --force I sure hope you know what you are doing.

   android-build-tools@1.3.0 install /usr/local/lib/node_modules/android-build-tools
   xbash install.bash

Accepting licenses
install.bash: line 153: sdkmanager.log: Permission denied
cat: sdkmanager.log: No such file or directory

ERROR: Install failed.

Please read output for clues, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).

Please note that JDK8 (not 9+) is required to install Android SDK. Get OpenJDK8 from https://adoptopenjdk.net/ and try again.
+ android-build-tools@1.3.0
updated 1 package in 5.217s
```

Issue created: https://github.com/mortend/android-build-tools/issues/7

**Comment by mortend** [comment]
Nice, thank you @Paulofsr.
