### ISSUE TITLE
icon.xml does not exist on Android

### ISSUE THREAD

**Issue by ckarmy** [fuse-open/uno#293]
In this commit (07436c0720f99c152a8d96b4fc913c03a54fb040) and later I get this error when I compile on Android

`node_modules\@fuse-open\uno\lib\build\UnoCore\1.15.0-canary.1\Targets\Android\Android.uxl(244.35): E0000: File \node_modules\@fuse-open\uno\lib\build\UnoCore\1.15.0-canary.1\Assets\icon.xml does not exist`

**Comment by AndrewEQ** [comment]
Will sort it out today

**Comment by AndrewEQ** [comment]
I just tested building on android without vector set in project settings and it compiled fine, could be that you're missing the file from your local repo?

Its definitely there: https://github.com/fuse-open/uno/pull/290/files
