### ISSUE TITLE
update to 1.14.0 ?

### ISSUE THREAD

**Issue by mmkevin** [fuse-open/uno#304]
hi i struggling to update UNO to 1.14.0 on my mac

when running uno --version im getting this output

$ uno --version
Uno version 1.14.0 (dev-build) macOS 10.14 x86_64 N/A
Copyright © 2018-present Fuse Open

but on a build its using uno 1.10.0 ?

$ fuse build --target=Android --configuration=Release 
Uno 1.10.0-rc1 (build 187) macOS 10.14 x86_64 b79b2df
Copyright © 2018-present Fuse Open

not sure what to do here

**Comment by ichan-mb** [comment]
Use this command instead: `uno build android -c release`

`fuse` command is part of Fuse Studio which has their own `uno` which is still stuck on ver 1.10.0-rc1
