### ISSUE TITLE
MetalANGLE as Metal wrapper for OpenGL ES on iOS

### ISSUE THREAD

**Issue by ichan-mb** [fuse-open/uno#320]
I saw this project named [MetalANGLE](https://github.com/kakashidinho/metalangle) a couple of days ago. It is a very interesting project. as it states in the readme :

> So the purpose of MetalANGLE is to allow OpenGL ES applications to continue to operate on Apple platforms by translating OpenGL ES draw calls to Metal draw calls under the hood

So is it feasible to use this wrapper/framework in our iOS target to transform our OpenGL rendering atop Metal? 

I think maybe if we use some kind of wrapper/translation layer to convert OpenGL rendering to Metal under the hood on iOS it will save a lot of time and effort than to do rewrite our engine from OpenGL to Metal.

**Comment by ichan-mb** [comment]
But I think the trade-off is our output binary will get bigger

**Comment by mortend** [comment]
Very interesting. Sounds promising.
