### ISSUE TITLE
use of undeclared identifier uStringToXliString

### ISSUE THREAD

**Issue by ckarmy** [fuse-open/uno#353]
I have a code to save a Panel to a image. That work fine but in the last version of Uno I get this error:
`use of undeclared identifier uStringToXliString`. I see that support.h file change completely.

This is an error or now I need to make some changes in my code to work again?

Thanks

The code:
[SignatureSavePanel.zip](https://github.com/fuse-open/uno/files/4870548/SignatureSavePanel.zip)

**Comment by mortend** [comment]
Hi,

The `uStringToXliString` helper method disappeared from `Uno/Support.h` in https://github.com/fuse-open/uno/pull/349/commits/0437e27eb457173dd87a4297dcf0bd59fc4cf86b.

We can use the `uCString` class to convert Uno strings to native C-strings instead.

Example:

```uno
uCString temp(path);
const char* ptr = temp.Ptr; // Memory is free'd when temp goes out of scope.
size_t length = temp.Length;
```

---

To fix your SignatureSavePanel code, edit near line 159 in `SavePanel.uno`.

Before:
```uno
			uImage::Png::Save(uStringToXliString(path), bmp);
```

After:
```uno
			uCString temp(path);
			uImage::Png::Save(temp.Ptr, bmp);
```

---

Thank you for testing!

**Comment by ckarmy** [comment]
Thanks! Now work again!
