### ISSUE TITLE
uno.h - Include nested too deeply

### ISSUE THREAD

**Issue by ckarmy** [fuse-open/uno#354]
In my app with lastest uno and fuselibs I get this error when I export my app in iOS release:

![image](https://user-images.githubusercontent.com/10090783/86618784-7ef99f00-bf87-11ea-937b-429b98a06b73.png)

My npm:
```
"devDependencies": {
        "@fuse-open/fuselibs": "https://ci.appveyor.com/api/buildjobs/1e5itniolluxteml/artifacts/fuse-open-fuselibs-2.0.0-beta.0.tgz",
        "@fuse-open/uno": "https://ci.appveyor.com/api/buildjobs/18pvechq14p4mbry/artifacts/fuse-open-uno-2.0.0-beta.3.tgz"
    }
```

**Comment by ckarmy** [comment]
Was a problem with git sorry

**Comment by ckarmy** [comment]
I think something related with this commit? https://github.com/fuse-open/uno/commit/52771bace264249ae2319b2c19b8afbd435d8def

**Comment by mortend** [comment]
Does the error persist if you first clean your project before building?

```
uno clean
```

**Comment by ckarmy** [comment]
Yes, I try `uno clean`, clean build folder from Xcode and deleting manualy node_folder, uno folder and build folder. And the error persist...

**Comment by ckarmy** [comment]
I downgrade to this and work fine. But I dont test from which version it fails

```
"devDependencies": {
        "@fuse-open/fuselibs": "https://ci.appveyor.com/api/buildjobs/bubgbup8hs1ytrio/artifacts/fuse-open-fuselibs-2.0.0-beta.0.tgz",
        "@fuse-open/uno": "https://ci.appveyor.com/api/buildjobs/8ife38d4s0i70vpu/artifacts/fuse-open-uno-2.0.0-beta.2.tgz"
},
```

**Comment by mortend** [comment]
Thank you for testing this.

I have made a patched version that I think will solve the problem.

https://ci.appveyor.com/api/buildjobs/fbjn07mn64e39smo/artifacts/fuse-open-uno-2.0.0-beta.3.tgz

**Comment by ckarmy** [comment]
Yes! Now work perfect!!! Thank you very much!!!
