### ISSUE TITLE
unoproj iOS.defines not working in latest Uno beta

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/uno#359]
Hi guys,

I'm not able to "auto compile" with COCOAPODS flag set in .unoproj via `iOS.defines: ['COCOAPODS']`. So the "defines" probably got disabled somewhere.

**Comment by mortend** [comment]
Regression confirmed.

I think it'll work again if you provide the property name in lower-case (`ios.defines`), but will provide a backwards-compatible fix for this shortly.

Thanks!

**Comment by AndrewEQ** [comment]
You're welcome, unfortunately the lower-case version didn't work for me, I shall use the `-DCOCOAPODS` cli option until the fix is out 👍
