### ISSUE TITLE
Unable to run iOS app on Simulator

### ISSUE THREAD

**Issue by ichan-mb** [fuse-open/uno#364]
On XCode 12 later, when building an app, it crashes with a log as seen below:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/10460131/96968038-93fc3d00-153a-11eb-80c7-1eef345bc9dc.png">

I guess it has something to do with a prebuilt library architecture

**Comment by mortend** [comment]
> Basically you have to exclude arm64 for simulator architecture both from your project and the Pod project,

https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Comment by mortend** [comment]
Fixed locally. PR coming soon.
