### ISSUE TITLE
Case Mismatch in Uno.Collections.unoproj File

### ISSUE THREAD

**Issue by choitapsi** [fuse-open/uno#522]
**Description:**

**Uno Version:**
2.9.2 (dev-build)

**Operating System:**
Debian 12

**Steps to Reproduce:**

1. Open the **Uno.Collections.unoproj** file.
2. Examine the "Includes" section.
3. Notice the case mismatch in filenames: **Enumerableextensions.uno** and **IListextensions.uno** instead of **EnumerableExtensions.uno** and **IListExtensions.uno**.

**Expected Behavior:**

Filenames in the "Includes" section should match the actual filenames with correct casing.

**Actual Behavior:**

Filenames in the "Includes" section have a case mismatch.

**Additional Information:**

This case mismatch may lead to build failures.

**Comment by mortend** [comment]
Thanks for reporting!
